# Generated by Django 3.0.5 on 2020-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='vote_target_id',
            new_name='vote_target',
        ),
        migrations.AddField(
            model_name='game',
            name='vote_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
