# Generated by Django 3.0.5 on 2020-04-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200411_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='vote_count',
            field=models.IntegerField(default=-1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='vote_yes_count',
            field=models.IntegerField(default=-1000),
        ),
    ]
