# Generated by Django 3.0.5 on 2020-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200417_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='vote_yes_count',
        ),
        migrations.AddField(
            model_name='player',
            name='vote',
            field=models.IntegerField(default=-1),
        ),
    ]
