# Generated by Django 3.0.5 on 2020-04-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200418_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_created', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='vote_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_created_at', to='game.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_voted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
